name: PysparkProject
description: ''
version: 0.0.1
author: sumitpaul@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: pysparkproject
  parentArtefactID: sumitpaulprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2026-01-27 07:40:36'
pipelines:
  pipelines/p1:
    name: p1
    description: ''
    author: sumitpaul@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2026-01-27 07:40:36'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2026-01-27 07:40:36'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2026-01-27T07:40:36.65333Z'
  name: plibMaven
  version: 8.16.1
  id: '1819950859'
  createdAt: '2026-01-27T07:40:36.65333Z'
  type: plibMaven
- modifiedAt: '2026-01-27T07:40:36.65333Z'
  name: plibPypi
  version: 2.1.9
  id: '1523359794'
  createdAt: '2026-01-27T07:40:36.65333Z'
  type: plibPypi
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.54
    isDefault: true
    author: null
    createdAt: '2026-01-27 07:40:16'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.10
    isDefault: true
    author: null
    createdAt: '2026-01-27 07:40:16'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
projectConfigurations: {}
